[phases.setup]
nixPkgs = [
"tesseract",
"tesseract5",
"leptonica",
"libpng",
"libjpeg",
"libtiff"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
